# Generated by Django 5.2.3 on 2025-06-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_readingexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
