# Generated by Django 5.2.3 on 2025-06-28 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_uploadcare_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
