# Generated by Django 5.2.3 on 2025-06-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uploadcare_uuid',
        ),
    ]
