# Generated by Django 5.2.3 on 2025-06-28 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_uploadcare_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploadcare_uuid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
