# Generated by Django 5.2.3 on 2025-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_book_file_remove_book_uploadcare_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file_uuid',
        ),
        migrations.AlterField(
            model_name='book',
            name='file_url',
            field=models.URLField(help_text='Paste raw GitHub URL to the PDF'),
        ),
    ]
