# Generated by Django 5.2.3 on 2025-08-09 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_file_uuid_alter_book_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file_url',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='books/'),
            preserve_default=False,
        ),
    ]
